---
# Install prerequisites
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

# Add Docker's GPG key
- name: Add Docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /tmp/docker.gpg
    apt-key add /tmp/docker.gpg

# Add Docker repository
- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

# Install Docker
- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

# Start and enable Docker
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

# Copy HTML file (index.html) into Docker container's web root
- name: Copy HTML file to Apache container
  copy:
    src: "C:/Users/vitalie.nivnea/DockerizeWithDevOps/index.html"  # Update with the actual path of your local HTML file
    dest: "/tmp/index.html"  # Temporary location in the container

# Run Apache container
- name: Start Apache container with mounted volume
  docker_container:
    name: apache-server
    image: httpd:latest
    state: started
    ports:
      - "80:80"
    volumes:
      - "C:/Users/vitalie.nivnea/DockerizeWithDevOps:/usr/local/apache2/htdocs"  # Mount local folder to container's web root

